# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R class to speed up builds and reduce memory
android.nonTransitiveRClass=true

# Allow Gradle to automatically download Android SDK components
android.builder.sdkDownload=true
android.experimental.dependency.excludeLibraryComponentsFromConstraints=true