import re
sh = 'app/src/main/java/com/my/salah/tracker/app/StatsHelper.java'
c = open(sh).read()
m = re.search(r'public\s+void\s+exportXls\s*\([^)]*\)\s*\{', c)
if m:
    s=m.start(); b=0; e=-1; im=False
    for i in range(s, len(c)):
        if c[i]=='{': b+=1; im=True
        elif c[i]=='}':
            b-=1
            if im and b==0: e=i+1; break
    if e!=-1:
        new_xls = """public void exportXls() {
        boolean isBn=sp.getString("app_lang","en").equals("bn");
        try{
            java.io.File dir=android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS); if(!dir.exists()) dir.mkdirs();
            java.io.File file=new java.io.File(dir,"Salah_Premium_Report_"+System.currentTimeMillis()+".xls"); java.io.PrintWriter pw=new java.io.PrintWriter(new java.io.OutputStreamWriter(new java.io.FileOutputStream(file),"UTF-8"));
            int tD=0,tDn=0,tM=0,tE=0,tQ=0,tExt=0; java.util.Calendar sumCal=(java.util.Calendar)statsCalPointer.clone(); sumCal.set(5,1);
            int mDays=sumCal.getActualMaximum(5); java.util.Calendar nowSum=java.util.Calendar.getInstance(); java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd",java.util.Locale.US);
            for(int j=1;j<=mDays;j++){sumCal.set(5,j); String dk=sdf.format(sumCal.getTime()); if(sumCal.after(nowSum)&&!dk.equals(sdf.format(nowSum.getTime())))continue;
            tD++; SalahRecord rec=getRoomRecord(dk); if(rec!=null){for(String p:prayers){String st=getFardStat(rec,p); if(st.equals("yes"))tDn++; else if(st.equals("excused"))tE++; else{if(getQazaStat(rec,p))tQ++; else tM++;}}} tExt+=getTotalExtras(dk);}
            int streak=ui.calculateStreak(sp,prayers); String title=(isBn?"মাসিক রিপোর্ট • ":"Monthly Report • ")+new java.text.SimpleDateFormat("MMMM yyyy",java.util.Locale.US).format(statsCalPointer.getTime());
            StringBuilder xml=new StringBuilder(); xml.append("<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?mso-application progid=\\"Excel.Sheet\\"?><Workbook xmlns=\\"urn:schemas-microsoft-com:office:spreadsheet\\" xmlns:ss=\\"urn:schemas-microsoft-com:office:spreadsheet\\"><Styles><Style ss:ID=\\"Default\\" ss:Name=\\"Normal\\"><Alignment ss:Vertical=\\"Center\\"/></Style>");
            xml.append("<Style ss:ID=\\"sTitle\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"22\\" ss:Bold=\\"1\\" ss:Color=\\"#FFFFFF\\"/><Interior ss:Color=\\"#10B981\\" ss:Pattern=\\"Solid\\"/></Style>");
            xml.append("<Style ss:ID=\\"sSumH\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"13\\" ss:Bold=\\"1\\" ss:Color=\\"#5F6368\\"/><Interior ss:Color=\\"#F8F9FA\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Top\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sSumV\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"16\\" ss:Bold=\\"1\\" ss:Color=\\"#202124\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"2\\" ss:Color=\\"#10B981\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sHead\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"14\\" ss:Bold=\\"1\\" ss:Color=\\"#FFFFFF\\"/><Interior ss:Color=\\"#334155\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"2\\" ss:Color=\\"#0F172A\\"/><Border ss:Position=\\"Top\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E0E0E0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sDate\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"12\\" ss:Bold=\\"1\\" ss:Color=\\"#334155\\"/><Interior ss:Color=\\"#F8FAFC\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Top\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sYes\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"12\\" ss:Bold=\\"1\\" ss:Color=\\"#059669\\"/><Interior ss:Color=\\"#D1FAE5\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sNo\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"12\\" ss:Bold=\\"1\\" ss:Color=\\"#DC2626\\"/><Interior ss:Color=\\"#FEE2E2\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sExc\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"12\\" ss:Bold=\\"1\\" ss:Color=\\"#7C3AED\\"/><Interior ss:Color=\\"#EDE9FE\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/></Borders></Style>");
            xml.append("<Style ss:ID=\\"sExt\\"><Alignment ss:Horizontal=\\"Center\\" ss:Vertical=\\"Center\\"/><Font ss:FontName=\\"Segoe UI\\" ss:Size=\\"12\\" ss:Bold=\\"1\\" ss:Color=\\"#D97706\\"/><Interior ss:Color=\\"#FEF3C7\\" ss:Pattern=\\"Solid\\"/><Borders><Border ss:Position=\\"Bottom\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Left\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/><Border ss:Position=\\"Right\\" ss:LineStyle=\\"Continuous\\" ss:Weight=\\"1\\" ss:Color=\\"#E2E8F0\\"/></Borders></Style>");
            xml.append("</Styles><Worksheet ss:Name=\\"Report\\"><Table><Column ss:Width=\\"150\\"/>");
            for(int i=0;i<6;i++)xml.append("<Column ss:Width=\\"115\\"/>"); xml.append("<Column ss:Width=\\"130\\"/><Column ss:Width=\\"160\\"/>");
            xml.append("<Row ss:Height=\\"70\\"><Cell ss:MergeAcross=\\"8\\" ss:StyleID=\\"sTitle\\"><Data ss:Type=\\"String\\">"+title+"</Data></Cell></Row>");
            String em=sp.getString("user_email","guest@salah.com"); xml.append("<Row ss:Height=\\"30\\"><Cell ss:MergeAcross=\\"8\\" ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+em+"</Data></Cell></Row><Row ss:Height=\\"20\\"><Cell><Data ss:Type=\\"String\\"></Data></Cell></Row>");
            xml.append("<Row ss:Height=\\"40\\"><Cell ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"মোট দিন":"Total Days")+"</Data></Cell><Cell ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"আদায়কৃত":"Done")+"</Data></Cell><Cell ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"কাজা":"Missed")+"</Data></Cell><Cell ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"অপেক্ষমান কাজা":"Pending Qaza")+"</Data></Cell><Cell ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"ছুটি":"Excused")+"</Data></Cell><Cell ss:MergeAcross=\\"1\\" ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"নফল/সুন্নাহ":"Extras")+"</Data></Cell><Cell ss:MergeAcross=\\"1\\" ss:StyleID=\\"sSumH\\"><Data ss:Type=\\"String\\">"+(isBn?"স্ট্রিক":"Streak")+"</Data></Cell></Row>");
            xml.append("<Row ss:Height=\\"50\\"><Cell ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tD)+"</Data></Cell><Cell ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tDn)+"</Data></Cell><Cell ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tM)+"</Data></Cell><Cell ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tQ)+"</Data></Cell><Cell ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tE)+"</Data></Cell><Cell ss:MergeAcross=\\"1\\" ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(tExt)+"</Data></Cell><Cell ss:MergeAcross=\\"1\\" ss:StyleID=\\"sSumV\\"><Data ss:Type=\\"String\\">"+lang.bnNum(streak)+" ★</Data></Cell></Row><Row ss:Height=\\"25\\"><Cell><Data ss:Type=\\"String\\"></Data></Cell></Row>");
            xml.append("<Row ss:Height=\\"45\\">"); String[] hdrs=isBn?new String[]{"তারিখ","ফজর","যোহর","আসর","মাগরিব","এশা","বিতর","অতিরিক্ত (নফল)","সারসংক্ষেপ"}:new String[]{"Date","Fajr","Dhuhr","Asr","Maghrib","Isha","Witr","Extras (Nafl)","Status"};
            for(String h:hdrs)xml.append("<Cell ss:StyleID=\\"sHead\\"><Data ss:Type=\\"String\\">"+h+"</Data></Cell>"); xml.append("</Row>");
            java.util.Calendar cal=(java.util.Calendar)statsCalPointer.clone(); cal.set(5,1);
            for(int i=1;i<=mDays;i++){cal.set(5,i); String dK=sdf.format(cal.getTime()); SalahRecord r=getRoomRecord(dK); String dDisp=isBn?lang.bnNum(i)+" "+lang.get(new java.text.SimpleDateFormat("MMM",java.util.Locale.US).format(cal.getTime()))+", "+lang.bnNum(cal.get(1)):dK;
            xml.append("<Row ss:Height=\\"40\\"><Cell ss:StyleID=\\"sDate\\"><Data ss:Type=\\"String\\">"+dDisp+"</Data></Cell>"); boolean aD=true; for(String p:prayers){String s=getFardStat(r,p); String sty=s.equals("yes")?"sYes":(s.equals("excused")?"sExc":"sNo"); String txt=s.equals("yes")?"\\u2713 "+(isBn?"সম্পন্ন":"Done"):(s.equals("excused")?"\\u273F "+(isBn?"ছুটি":"Excused"):"\\u2715 "+(isBn?"কাজা":"Missed")); xml.append("<Cell ss:StyleID=\\""+sty+"\\"><Data ss:Type=\\"String\\">"+txt+"</Data></Cell>"); if(!s.equals("yes")&&!s.equals("excused"))aD=false;}
            int dEx=getTotalExtras(dK); String exTxt=dEx>0?"+ "+lang.bnNum(dEx):"-"; xml.append("<Cell ss:StyleID=\\"sExt\\"><Data ss:Type=\\"String\\">"+exTxt+"</Data></Cell>");
            String sSt=aD?"sYes":"sNo"; String sTxt=aD?(isBn?"★ আলহামদুলিল্লাহ":"★ Perfect"):(isBn?"⚠ অসম্পূর্ণ":"⚠ Incomplete"); xml.append("<Cell ss:StyleID=\\""+sSt+"\\"><Data ss:Type=\\"String\\">"+sTxt+"</Data></Cell></Row>");}
            xml.append("</Table></Worksheet></Workbook>"); pw.write(xml.toString()); pw.close();
            final java.io.File fF=file; ui.showSmartBanner((android.widget.FrameLayout)activity.findViewById(android.R.id.content),isBn?"সফল":"Success",isBn?"XLS ফাইল সেভ হয়েছে (ওপেন করতে ক্লিক)":"XLS Saved","img_tick",colorAccent,()->{android.content.Intent i=new android.content.Intent(android.content.Intent.ACTION_VIEW); i.setDataAndType(androidx.core.content.FileProvider.getUriForFile(activity,activity.getPackageName()+".provider",fF),"application/vnd.ms-excel"); i.addFlags(1); activity.startActivity(android.content.Intent.createChooser(i,"Open with..."));});
        }catch(Exception e){}
    }"""
        c = c[:s] + new_xls + c[e:]
open(sh,'w').write(c)
print("✅ Part 2 Done!")
