ma = 'app/src/main/java/com/my/salah/tracker/app/MainActivity.java'
c = open(ma).read()

# Add Nafl UI Render
c_render = """// CUSTOM NAFL
        String cStr = sp.getString("custom_nafl_list", "");
        if(!cStr.isEmpty()) {
            for(final String cItem : cStr.split(",")) {
                if(cItem.trim().isEmpty()) continue;
                String[] pts = cItem.split(":"); final String cName = pts[0]; final String cRak = pts.length>1?pts[1]:"2";
                final String cKey = selectedDate[0] + "_Custom_" + cName; final boolean cStat = sp.getString(cKey, "no").equals("yes");
                android.widget.LinearLayout cCard = new android.widget.LinearLayout(this); cCard.setPadding((int)(15*DENSITY), (int)(cardPadV*DENSITY), (int)(20*DENSITY), (int)(cardPadV*DENSITY)); cCard.setGravity(android.view.Gravity.CENTER_VERTICAL);
                android.graphics.drawable.GradientDrawable cb = new android.graphics.drawable.GradientDrawable(); cb.setColor(themeColors[1]); cb.setStroke((int)(1.5f*DENSITY), cStat ? android.graphics.Color.parseColor("#F59E0B") : themeColors[4]); cb.setCornerRadius(25f * DENSITY); cCard.setBackground(cb);
                android.widget.LinearLayout.LayoutParams cLp = new android.widget.LinearLayout.LayoutParams(-1, -2); cLp.setMargins(0, 0, 0, (int)(cardMarB*DENSITY)); cCard.setLayoutParams(cLp);
                android.widget.TextView cIcon = new android.widget.TextView(this); cIcon.setText("⭐"); cIcon.setTextSize(18); cIcon.setGravity(android.view.Gravity.CENTER); android.graphics.drawable.GradientDrawable icBg = new android.graphics.drawable.GradientDrawable(); icBg.setShape(android.graphics.drawable.GradientDrawable.OVAL); icBg.setColor(themeColors[5]); cIcon.setBackground(icBg);
                android.widget.LinearLayout.LayoutParams icCardLp = new android.widget.LinearLayout.LayoutParams((int)(38*DENSITY), (int)(38*DENSITY)); icCardLp.setMargins(0,0,(int)(15*DENSITY),0); cIcon.setLayoutParams(icCardLp); cCard.addView(cIcon);
                android.widget.LinearLayout tCon = new android.widget.LinearLayout(this); tCon.setOrientation(android.widget.LinearLayout.VERTICAL); tCon.setLayoutParams(new android.widget.LinearLayout.LayoutParams(0, -2, 1f));
                android.widget.TextView tv = new android.widget.TextView(this); tv.setText(cName); tv.setTextColor(themeColors[2]); tv.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); tv.setTextSize(16); tv.setSingleLine(true); tCon.addView(tv);
                android.widget.TextView tvR = new android.widget.TextView(this); tvR.setText(lang.bnNum(cRak) + " " + lang.get("Rakats")); tvR.setTextColor(themeColors[3]); tvR.setTextSize(12); tCon.addView(tvR); cCard.addView(tCon);
                final android.view.View chk = ui.getPremiumCheckbox(cStat?"yes":"no", android.graphics.Color.parseColor("#F59E0B")); cCard.addView(chk);
                cCard.setOnClickListener(new android.view.View.OnClickListener() { @Override public void onClick(final android.view.View v) { v.performHapticFeedback(android.view.HapticFeedbackConstants.VIRTUAL_KEY); boolean newVal = !sp.getString(cKey, "no").equals("yes"); sp.edit().putString(cKey, newVal ? "yes" : "no").apply(); fbHelper.save(selectedDate[0], "Custom_" + cName, newVal ? "yes" : "no"); v.animate().scaleX(0.95f).scaleY(0.95f).alpha(0.8f).setDuration(100).withEndAction(new Runnable() { @Override public void run() { v.animate().scaleX(1f).scaleY(1f).alpha(1f).setDuration(250).setInterpolator(new android.view.animation.OvershootInterpolator()).start(); } }).start(); v.postDelayed(new Runnable() { @Override public void run() { loadTodayPage(); refreshWidget(); }}, 150); } });
                cCard.setOnLongClickListener(new android.view.View.OnLongClickListener() { @Override public boolean onLongClick(android.view.View v) { v.performHapticFeedback(android.view.HapticFeedbackConstants.LONG_PRESS); showDeleteCustomPrayerDialog(cName); return true; } });
                cardsContainer.addView(cCard);
            }
        }
        android.widget.LinearLayout addBtn = new android.widget.LinearLayout(this); addBtn.setPadding((int)(15*DENSITY), (int)(15*DENSITY), (int)(15*DENSITY), (int)(15*DENSITY)); addBtn.setGravity(android.view.Gravity.CENTER); android.graphics.drawable.GradientDrawable aBg = new android.graphics.drawable.GradientDrawable(); aBg.setColor(themeColors[4]); aBg.setCornerRadius(20f*DENSITY); addBtn.setBackground(aBg);
        android.widget.LinearLayout.LayoutParams aLp = new android.widget.LinearLayout.LayoutParams(-1, -2); aLp.setMargins(0, (int)(10*DENSITY), 0, (int)(20*DENSITY)); addBtn.setLayoutParams(aLp);
        android.widget.TextView aTxt = new android.widget.TextView(this); aTxt.setText("➕  " + lang.get("Add Extra Prayer")); aTxt.setTextColor(themeColors[2]); aTxt.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); addBtn.addView(aTxt);
        addBtn.setOnClickListener(new android.view.View.OnClickListener() { @Override public void onClick(android.view.View v) { v.performHapticFeedback(android.view.HapticFeedbackConstants.VIRTUAL_KEY); showAddCustomPrayerDialog(); } });
        cardsContainer.addView(addBtn);
        contentArea.addView(cardsContainer);"""
c = c.replace('contentArea.addView(cardsContainer);', c_render)

# Add Dialogs
dialogs = """private void showAddCustomPrayerDialog() {
        android.widget.FrameLayout wrap = new android.widget.FrameLayout(this); wrap.setLayoutParams(new android.widget.FrameLayout.LayoutParams(-1, -1));
        android.widget.LinearLayout main = new android.widget.LinearLayout(this); main.setOrientation(android.widget.LinearLayout.VERTICAL); main.setPadding((int)(25*DENSITY), (int)(30*DENSITY), (int)(25*DENSITY), (int)(30*DENSITY)); android.graphics.drawable.GradientDrawable gd = new android.graphics.drawable.GradientDrawable(); gd.setColor(themeColors[1]); gd.setCornerRadius(30f * DENSITY); main.setBackground(gd);
        android.widget.TextView iconView = new android.widget.TextView(this); iconView.setText("⭐"); iconView.setTextSize(40); iconView.setGravity(android.view.Gravity.CENTER); main.addView(iconView);
        android.widget.TextView title = new android.widget.TextView(this); title.setText(lang.get("Add Extra Prayer")); title.setTextColor(themeColors[2]); title.setTextSize(20); title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); title.setGravity(android.view.Gravity.CENTER); title.setPadding(0, (int)(10*DENSITY), 0, (int)(25*DENSITY)); main.addView(title);
        final android.widget.EditText nameIn = new android.widget.EditText(this); nameIn.setHint(lang.get("Prayer Name (e.g. Ishraq)")); nameIn.setTextColor(themeColors[2]); nameIn.setHintTextColor(themeColors[3]); android.graphics.drawable.GradientDrawable iBg = new android.graphics.drawable.GradientDrawable(); iBg.setColor(themeColors[4]); iBg.setCornerRadius(15f*DENSITY); nameIn.setBackground(iBg); nameIn.setPadding((int)(20*DENSITY),(int)(15*DENSITY),(int)(20*DENSITY),(int)(15*DENSITY)); main.addView(nameIn, new android.widget.LinearLayout.LayoutParams(-1, -2));
        final android.widget.EditText rakIn = new android.widget.EditText(this); rakIn.setHint(lang.get("Rakats (e.g. 2)")); rakIn.setInputType(android.text.InputType.TYPE_CLASS_NUMBER); rakIn.setTextColor(themeColors[2]); rakIn.setHintTextColor(themeColors[3]); rakIn.setBackground(iBg); rakIn.setPadding((int)(20*DENSITY),(int)(15*DENSITY),(int)(20*DENSITY),(int)(15*DENSITY)); android.widget.LinearLayout.LayoutParams rLp = new android.widget.LinearLayout.LayoutParams(-1, -2); rLp.setMargins(0,(int)(10*DENSITY),0,(int)(25*DENSITY)); main.addView(rakIn, rLp);
        android.widget.Button btn = new android.widget.Button(this); btn.setText(lang.get("Add Prayer")); btn.setTextColor(android.graphics.Color.WHITE); btn.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); btn.setAllCaps(false); android.graphics.drawable.GradientDrawable bBg = new android.graphics.drawable.GradientDrawable(); bBg.setColor(android.graphics.Color.parseColor("#F59E0B")); bBg.setCornerRadius(20f*DENSITY); btn.setBackground(bBg); main.addView(btn, new android.widget.LinearLayout.LayoutParams(-1, (int)(55*DENSITY)));
        android.widget.FrameLayout.LayoutParams flp = new android.widget.FrameLayout.LayoutParams((int)(320*DENSITY), -2); flp.gravity = android.view.Gravity.CENTER; wrap.addView(main, flp);
        final android.app.AlertDialog ad = new android.app.AlertDialog.Builder(this).setView(wrap).create(); ad.getWindow().setBackgroundDrawableResource(android.R.color.transparent); ad.getWindow().setGravity(android.view.Gravity.CENTER); applyFont(main, appFonts[0], appFonts[1]);
        btn.setOnClickListener(new android.view.View.OnClickListener(){@Override public void onClick(android.view.View v){
            String n = nameIn.getText().toString().trim().replace(":", "").replace(",", ""); String r = rakIn.getText().toString().trim();
            if(!n.isEmpty()) { String cList = sp.getString("custom_nafl_list", ""); sp.edit().putString("custom_nafl_list", cList + (cList.isEmpty()?"":",") + n + ":" + (r.isEmpty()?"2":r)).apply(); ad.dismiss(); loadTodayPage(); refreshWidget(); }
        }}); ad.show();
    }
    private void showDeleteCustomPrayerDialog(final String cName) {
        android.widget.FrameLayout wrap = new android.widget.FrameLayout(this); wrap.setLayoutParams(new android.widget.FrameLayout.LayoutParams(-1, -1)); android.widget.LinearLayout main = new android.widget.LinearLayout(this); main.setOrientation(android.widget.LinearLayout.VERTICAL); main.setPadding((int)(25*DENSITY), (int)(30*DENSITY), (int)(25*DENSITY), (int)(30*DENSITY)); android.graphics.drawable.GradientDrawable gd = new android.graphics.drawable.GradientDrawable(); gd.setColor(themeColors[1]); gd.setCornerRadius(25f * DENSITY); main.setBackground(gd);
        android.widget.TextView title = new android.widget.TextView(this); title.setText(lang.get("Delete Extra Prayer?")); title.setTextColor(android.graphics.Color.parseColor("#FF5252")); title.setTextSize(20); title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); title.setGravity(android.view.Gravity.CENTER); main.addView(title);
        android.widget.TextView sub = new android.widget.TextView(this); sub.setText(lang.get("This will remove it from your list.")); sub.setTextColor(themeColors[3]); sub.setGravity(android.view.Gravity.CENTER); sub.setPadding(0,(int)(10*DENSITY),0,(int)(25*DENSITY)); main.addView(sub);
        android.widget.LinearLayout row = new android.widget.LinearLayout(this); row.setOrientation(android.widget.LinearLayout.HORIZONTAL);
        android.widget.Button btnC = new android.widget.Button(this); btnC.setText(lang.get("CANCEL")); btnC.setTextColor(themeColors[2]); btnC.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); btnC.setAllCaps(false); android.graphics.drawable.GradientDrawable cBg = new android.graphics.drawable.GradientDrawable(); cBg.setColor(themeColors[4]); cBg.setCornerRadius(15f*DENSITY); btnC.setBackground(cBg); android.widget.LinearLayout.LayoutParams lpC = new android.widget.LinearLayout.LayoutParams(0, (int)(50*DENSITY), 1f); lpC.setMargins(0,0,(int)(10*DENSITY),0); row.addView(btnC, lpC);
        android.widget.Button btnD = new android.widget.Button(this); btnD.setText(lang.get("Delete")); btnD.setTextColor(android.graphics.Color.WHITE); btnD.setTypeface(android.graphics.Typeface.DEFAULT_BOLD); btnD.setAllCaps(false); android.graphics.drawable.GradientDrawable dBg = new android.graphics.drawable.GradientDrawable(); dBg.setColor(android.graphics.Color.parseColor("#FF5252")); dBg.setCornerRadius(15f*DENSITY); btnD.setBackground(dBg); row.addView(btnD, new android.widget.LinearLayout.LayoutParams(0, (int)(50*DENSITY), 1f)); main.addView(row);
        android.widget.FrameLayout.LayoutParams flp = new android.widget.FrameLayout.LayoutParams((int)(320*DENSITY), -2); flp.gravity = android.view.Gravity.CENTER; wrap.addView(main, flp);
        final android.app.AlertDialog ad = new android.app.AlertDialog.Builder(this).setView(wrap).create(); ad.getWindow().setBackgroundDrawableResource(android.R.color.transparent); ad.getWindow().setGravity(android.view.Gravity.CENTER); applyFont(main, appFonts[0], appFonts[1]);
        btnC.setOnClickListener(new android.view.View.OnClickListener(){@Override public void onClick(android.view.View v){ad.dismiss();}});
        btnD.setOnClickListener(new android.view.View.OnClickListener(){@Override public void onClick(android.view.View v){ String cList = sp.getString("custom_nafl_list", ""); String[] pts = cList.split(","); StringBuilder sb = new StringBuilder(); for(String p : pts) { if(!p.startsWith(cName+":") && !p.equals(cName)) { sb.append(p).append(","); } } String res = sb.toString(); if(res.endsWith(",")) res = res.substring(0, res.length()-1); sp.edit().putString("custom_nafl_list", res).apply(); ad.dismiss(); loadTodayPage(); refreshWidget(); }}); ad.show();
    }\n}"""
if 'showAddCustomPrayerDialog' not in c: c = c[:c.rfind('}')] + dialogs
open(ma,'w').write(c)
print("✅ Part 3 Done! NOW YOU CAN BUILD THE APP.")
