f = 'app/src/main/java/com/my/salah/tracker/app/MainActivity.java'
c = open(f, 'r', encoding='utf-8').read()
canvas_pt2 = r'''
        private void count(boolean add) { int i=zikrMan.currentIdx; ZikrManager.TasbihData d=zikrMan.tasbihList.get(i); if(add){ zikrMan.indCounts[i]++; if(zikrMan.soundOn&&zikrMan.toneGen!=null) zikrMan.toneGen.startTone(24,50); if(d.target>0&&zikrMan.indCounts[i]>=d.target){zikrMan.indCounts[i]=0; zikrMan.indRounds[i]++; performHapticFeedback(0);} } else { if(zikrMan.indCounts[i]>0){zikrMan.indCounts[i]--;} } zikrMan.save(); }
        private void anim(float t, boolean a) { android.animation.ValueAnimator v=android.animation.ValueAnimator.ofFloat(beadOffset,t); v.setDuration(120); v.addUpdateListener(an->{beadOffset=(float)an.getAnimatedValue();invalidate();}); v.addListener(new android.animation.AnimatorListenerAdapter(){public void onAnimationEnd(android.animation.Animator an){if(t!=0f)count(a); beadOffset=0f;invalidate();}}); v.start(); }
        
        @Override public boolean onTouchEvent(android.view.MotionEvent ev) {
            float x=ev.getX(), y=ev.getY(), w=getWidth(), cx=w/2f; float topY=100f, cY=topY+380f, rad=w*0.33f, strY=cY+rad+100f, boxT=strY+100f, boxB=boxT+320f, iY=boxB+110f, thY=iY+160f; int i=zikrMan.currentIdx;
            if(ev.getAction()==0){startX=x;startY=y;isSwiping=false;return true;}
            if(ev.getAction()==2){float dx=x-startX; if(Math.abs(dx)>20){isSwiping=true; beadOffset=dx; if(beadOffset>160f)beadOffset=160f; if(beadOffset<-160f)beadOffset=-160f; invalidate();}}
            if(ev.getAction()==1){
                float dx=x-startX; if(isSwiping){ if(dx<-60){performHapticFeedback(1);anim(-160f,true);} else if(dx>60){performHapticFeedback(1);anim(160f,false);} else anim(0f,false); }
                else {
                    if(Math.abs(y-iY)<80){ if(x<200){performHapticFeedback(1); new android.app.AlertDialog.Builder(getContext()).setTitle(lang.get("Reset")).setMessage(lang.get("Do you want to reset counts for this Dua?")).setPositiveButton("Yes",(di,wi)->{zikrMan.indCounts[i]=0;zikrMan.indRounds[i]=0;zikrMan.save();invalidate();}).setNegativeButton("No",null).show();} else if(x>w-200){performHapticFeedback(1);zikrMan.soundOn=!zikrMan.soundOn;zikrMan.save();invalidate();} }
                    else if(y>cY-80 && y<cY+80 && x>cx){performHapticFeedback(1); final android.widget.EditText et=new android.widget.EditText(getContext()); et.setInputType(2); et.setText(String.valueOf(zikrMan.tasbihList.get(i).target)); new android.app.AlertDialog.Builder(getContext()).setTitle(lang.get("Target")).setView(et).setPositiveButton("OK",(di,wi)->{if(!et.getText().toString().isEmpty()){zikrMan.tasbihList.get(i).target=Integer.parseInt(et.getText().toString()); zikrMan.prefs.edit().putInt("target_"+i,zikrMan.tasbihList.get(i).target).apply(); invalidate();}}).show();}
                    else if(y>boxT && y<boxB && x>40 && x<w-40){performHapticFeedback(1); showList();}
                    else if(y>thY-60 && y<thY+60){ float sX=cx-250f; for(int j=0;j<6;j++){ if(Math.abs(x-(sX+(j*100f)))<50){performHapticFeedback(1);zikrMan.beadTheme=j;zikrMan.save();invalidate();break;} } }
                    else {performHapticFeedback(1);anim(-160f,true);}
                }
            } return true;
        }
        
        private void showList(){
            final android.app.Dialog d=new android.app.Dialog(getContext(),android.R.style.Theme_Black_NoTitleBar_Fullscreen); android.widget.LinearLayout r=new android.widget.LinearLayout(getContext()); r.setOrientation(1); r.setBackgroundColor(themeColors[0]); r.setPadding(40,80,40,40); android.widget.TextView t1=new android.widget.TextView(getContext()); t1.setText(lang.get("Zikr")); t1.setTextColor(colorAccent); t1.setTextSize(26); t1.setTypeface(appFonts[1]); t1.setGravity(1); r.addView(t1);
            android.widget.ScrollView sv=new android.widget.ScrollView(getContext()); android.widget.LinearLayout l=new android.widget.LinearLayout(getContext()); l.setOrientation(1);
            for(int j=0;j<zikrMan.tasbihList.size();j++){
                final int rI=j; ZikrManager.TasbihData dt=zikrMan.tasbihList.get(j); android.widget.LinearLayout row=new android.widget.LinearLayout(getContext()); row.setOrientation(1); row.setPadding(30,45,30,45); row.setGravity(17);
                android.widget.TextView tA=new android.widget.TextView(getContext()); tA.setText(dt.arabic); tA.setTextColor(themeColors[2]); tA.setTextSize(32); tA.setTypeface(getArabicFont()); tA.setGravity(17); tA.setOnClickListener(v->{zikrMan.currentIdx=rI;zikrMan.save();invalidate();d.dismiss();}); row.addView(tA);
                android.widget.TextView tP=new android.widget.TextView(getContext()); tP.setText(dt.pron); tP.setTextColor(themeColors[3]); tP.setTextSize(16); tP.setTypeface(appFonts[0]); tP.setGravity(17); tP.setPadding(0,15,0,5); row.addView(tP);
                android.widget.TextView tM=new android.widget.TextView(getContext()); tM.setText(dt.mean); tM.setTextColor(themeColors[3]); tM.setTextSize(14); tM.setTypeface(appFonts[0]); tM.setGravity(17); tM.setPadding(0,0,0,25); row.addView(tM);
                android.widget.TextView tT=new android.widget.TextView(getContext()); tT.setText("Target: "+dt.target); tT.setTextColor(colorAccent); tT.setTextSize(18); tT.setTypeface(appFonts[1]); tT.setGravity(17); android.graphics.drawable.GradientDrawable tb=new android.graphics.drawable.GradientDrawable(); tb.setColor(themeColors[1]); tb.setCornerRadius(15f); tT.setBackground(tb); tT.setPadding(40,15,40,15); tT.setOnClickListener(v->{ final android.widget.EditText et=new android.widget.EditText(getContext()); et.setInputType(2); et.setText(String.valueOf(zikrMan.tasbihList.get(rI).target)); new android.app.AlertDialog.Builder(getContext()).setTitle(lang.get("Target")).setView(et).setPositiveButton("OK",(di,wi)->{if(!et.getText().toString().isEmpty()){zikrMan.tasbihList.get(rI).target=Integer.parseInt(et.getText().toString()); tT.setText("Target: "+et.getText().toString()); zikrMan.prefs.edit().putInt("target_"+rI, zikrMan.tasbihList.get(rI).target).apply(); invalidate();}}).show(); }); row.addView(tT);
                l.addView(row); android.view.View div=new android.view.View(getContext()); div.setBackgroundColor(themeColors[4]); div.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1,2)); l.addView(div);
            } sv.addView(l); r.addView(sv,new android.widget.LinearLayout.LayoutParams(-1,0,1f));
            android.widget.Button bA=new android.widget.Button(getContext()); bA.setText("+ Add New"); bA.setAllCaps(false); bA.setTextColor(colorAccent); bA.setTypeface(appFonts[1]); android.graphics.drawable.GradientDrawable btnBg=new android.graphics.drawable.GradientDrawable(); btnBg.setColor(android.graphics.Color.TRANSPARENT); btnBg.setStroke(4, colorAccent); btnBg.setCornerRadius(30f); bA.setBackground(btnBg); android.widget.LinearLayout.LayoutParams blp=new android.widget.LinearLayout.LayoutParams(-1,150); blp.setMargins(40,30,40,40); bA.setLayoutParams(blp);
            bA.setOnClickListener(v->{ android.widget.LinearLayout lay=new android.widget.LinearLayout(getContext()); lay.setOrientation(1); lay.setPadding(50,20,50,20); final android.widget.EditText eD=new android.widget.EditText(getContext()); eD.setHint("Arabic Dua"); final android.widget.EditText eP=new android.widget.EditText(getContext()); eP.setHint("উচ্চারণ"); final android.widget.EditText eM=new android.widget.EditText(getContext()); eM.setHint("অর্থ"); final android.widget.EditText eT=new android.widget.EditText(getContext()); eT.setHint("Target"); eT.setInputType(2); lay.addView(eD); lay.addView(eP); lay.addView(eM); lay.addView(eT); new android.app.AlertDialog.Builder(getContext()).setTitle("Add").setView(lay).setPositiveButton("OK",(di,wi)->{if(!eD.getText().toString().isEmpty()){zikrMan.tasbihList.add(new ZikrManager.TasbihData(eD.getText().toString(),Integer.parseInt(eT.getText().toString().isEmpty()?"0":eT.getText().toString()),eP.getText().toString(),eM.getText().toString())); zikrMan.save(); invalidate(); d.dismiss();}}).show(); }); r.addView(bA); d.setContentView(r); d.show();
        }
    }
    private void loadZikrTab() { contentArea.removeAllViews(); contentArea.addView(new ZikrCanvasView(this), new android.widget.LinearLayout.LayoutParams(-1,-1)); }
'''
c = c.replace('// ZIKR_EVENTS_PLACEHOLDER', canvas_pt2)
open(f, 'w', encoding='utf-8').write(c)
print("✅ Step 4: Touch Events & List Modal Ready. YOU CAN BUILD NOW!")
